name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Execute SSH commands on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ~/projects/nexus_ai_bot
          # Сбрасываем все локальные изменения, чтобы git pull не ругался
          git fetch origin main
          git reset --hard origin/main
          
          # Устанавливаем зависимости (на случай, если ты добавил новые библиотеки)
          ./.venv/bin/pip install -r requirements.txt
          
          # Перезапускаем службу
          systemctl restart nexusbot
          
          # Проверяем статус через 2 секунды, чтобы убедиться, что бот не упал
          sleep 2
          systemctl status nexusbot